-- HSR Leader Board: cloud-only daily/monthly workflow
-- Safe additive migration. Existing app_users, states and team_persons rows are preserved.

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  person_id text not null,
  state_id text not null,
  person_name text not null,
  plan_data jsonb not null default '{}'::jsonb,
  actual_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entry_date, person_id)
);

create index if not exists daily_entries_person_date_idx
  on public.daily_entries (person_id, entry_date desc);

create table if not exists public.monthly_snapshots (
  id bigint generated by default as identity primary key,
  month_key text not null,
  person_id text not null,
  state_id text not null,
  person_name text not null,
  plan_data jsonb not null default '{}'::jsonb,
  actual_data jsonb not null default '{}'::jsonb,
  full_data jsonb not null default '{}'::jsonb,
  data jsonb not null default '{}'::jsonb,
  daily_records jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  archived_at timestamptz not null default now(),
  unique (month_key, person_id)
);

-- Upgrade the legacy monthly_snapshots table if it already exists.
alter table public.monthly_snapshots add column if not exists person_name text not null default '';
alter table public.monthly_snapshots add column if not exists plan_data jsonb not null default '{}'::jsonb;
alter table public.monthly_snapshots add column if not exists actual_data jsonb not null default '{}'::jsonb;
alter table public.monthly_snapshots add column if not exists full_data jsonb not null default '{}'::jsonb;
alter table public.monthly_snapshots add column if not exists data jsonb not null default '{}'::jsonb;
alter table public.monthly_snapshots add column if not exists daily_records jsonb not null default '[]'::jsonb;
alter table public.monthly_snapshots add column if not exists created_at timestamptz not null default now();
alter table public.monthly_snapshots add column if not exists archived_at timestamptz not null default now();

create unique index if not exists monthly_snapshots_month_person_uidx
  on public.monthly_snapshots (month_key, person_id);

create index if not exists monthly_snapshots_person_month_idx
  on public.monthly_snapshots (person_id, month_key desc);

alter table public.app_settings enable row level security;
alter table public.daily_entries enable row level security;
alter table public.monthly_snapshots enable row level security;

drop policy if exists "app_settings_cloud_access" on public.app_settings;
create policy "app_settings_cloud_access" on public.app_settings
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "daily_entries_cloud_access" on public.daily_entries;
create policy "daily_entries_cloud_access" on public.daily_entries
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "monthly_snapshots_cloud_access" on public.monthly_snapshots;
create policy "monthly_snapshots_cloud_access" on public.monthly_snapshots
  for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.app_settings to anon, authenticated;
grant select, insert, update, delete on public.daily_entries to anon, authenticated;
grant select, insert, update, delete on public.monthly_snapshots to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'daily_entries'
  ) then
    alter publication supabase_realtime add table public.daily_entries;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'monthly_snapshots'
  ) then
    alter publication supabase_realtime add table public.monthly_snapshots;
  end if;
end;
$$;

create or replace function public.hsr_rollover(
  p_today date default ((now() at time zone 'Asia/Kolkata')::date)
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last_date date;
  v_month_changed boolean;
  v_month_key text;
begin
  perform pg_advisory_xact_lock(hashtext('hsr-leader-board-rollover'));

  insert into public.app_settings (key, value, updated_at)
  values ('business_calendar', jsonb_build_object('business_date', p_today::text), now())
  on conflict (key) do nothing;

  select (value ->> 'business_date')::date
    into v_last_date
  from public.app_settings
  where key = 'business_calendar'
  for update;

  if v_last_date is null then
    update public.app_settings
      set value = jsonb_build_object('business_date', p_today::text), updated_at = now()
    where key = 'business_calendar';
    return jsonb_build_object('status', 'initialized', 'business_date', p_today);
  end if;

  if v_last_date >= p_today then
    return jsonb_build_object('status', 'current', 'business_date', v_last_date);
  end if;

  v_month_changed := date_trunc('month', v_last_date) <> date_trunc('month', p_today);
  v_month_key := to_char(v_last_date, 'YYYY-MM');

  -- Preserve the final values entered for the previous business day.
  insert into public.daily_entries (
    entry_date, person_id, state_id, person_name, plan_data, actual_data, updated_at
  )
  select
    v_last_date,
    tp.person_id,
    tp.state_id,
    tp.name,
    jsonb_build_object(
      'sales', coalesce(tp.today_plan_sales, 0),
      'collection', coalesce(tp.today_plan_collection, 0),
      'farmerContact', coalesce(tp.today_plan_farmer_contact, 0),
      'gfm', coalesce(tp.today_plan_gfm, 0),
      'ofm', coalesce(tp.today_plan_ofm, 0),
      'nightHalt', coalesce(tp.today_plan_night_halt, 0),
      'dilutionTest', coalesce(tp.today_plan_dilution_test, 0),
      'demos', coalesce(tp.today_plan_demos, 0),
      'fieldVisit', coalesce(tp.today_plan_field_visit, 0),
      'fieldDay', coalesce(tp.today_plan_field_day, 0),
      'dealerAppointment', coalesce(tp.today_plan_dealer_appointment, 0),
      'dealerAppointed', coalesce(tp.today_plan_dealer_appointed, 0)
    ),
    jsonb_build_object(
      'sales', coalesce(tp.today_sales, 0),
      'collection', coalesce(tp.today_collection, 0),
      'farmerContact', coalesce(tp.today_farmer_contact, 0),
      'gfm', coalesce(tp.today_gfm, 0),
      'ofm', coalesce(tp.today_ofm, 0),
      'nightHalt', coalesce(tp.today_night_halt, 0),
      'dilutionTest', coalesce(tp.today_dilution_test, 0),
      'demos', coalesce(tp.today_demos, 0),
      'fieldVisit', coalesce(tp.today_field_visit, 0),
      'fieldDay', coalesce(tp.today_field_day, 0),
      'dealerAppointment', coalesce(tp.today_dealer_appointment, 0),
      'dealerAppointed', coalesce(tp.today_dealer_appointed, 0)
    ),
    now()
  from public.team_persons tp
  on conflict (entry_date, person_id) do update set
    state_id = excluded.state_id,
    person_name = excluded.person_name,
    plan_data = excluded.plan_data,
    actual_data = excluded.actual_data,
    updated_at = now();

  -- Only daily actuals are accumulated into monthly actuals.
  update public.team_persons set
    sales = coalesce(sales, 0) + coalesce(today_sales, 0),
    collection = coalesce(collection, 0) + coalesce(today_collection, 0),
    farmer_contact = coalesce(farmer_contact, 0) + coalesce(today_farmer_contact, 0),
    gfm = coalesce(gfm, 0) + coalesce(today_gfm, 0),
    ofm = coalesce(ofm, 0) + coalesce(today_ofm, 0),
    night_halt = coalesce(night_halt, 0) + coalesce(today_night_halt, 0),
    dilution_test = coalesce(dilution_test, 0) + coalesce(today_dilution_test, 0),
    demos = coalesce(demos, 0) + coalesce(today_demos, 0),
    field_visit = coalesce(field_visit, 0) + coalesce(today_field_visit, 0),
    field_day = coalesce(field_day, 0) + coalesce(today_field_day, 0),
    dealer_appointment = coalesce(dealer_appointment, 0) + coalesce(today_dealer_appointment, 0),
    dealer_appointed = coalesce(dealer_appointed, 0) + coalesce(today_dealer_appointed, 0);

  if v_month_changed then
    -- Archive the completed month after its final daily actual has been accumulated.
    insert into public.monthly_snapshots (
      month_key, person_id, state_id, person_name,
      plan_data, actual_data, full_data, data, daily_records, archived_at
    )
    select
      v_month_key,
      tp.person_id,
      tp.state_id,
      tp.name,
      jsonb_build_object(
        'sales', coalesce(tp.plan_sales, 0),
        'collection', coalesce(tp.plan_collection, 0),
        'farmerContact', coalesce(tp.plan_farmer_contact, 0),
        'gfm', coalesce(tp.plan_gfm, 0),
        'ofm', coalesce(tp.plan_ofm, 0),
        'nightHalt', coalesce(tp.plan_night_halt, 0),
        'dilutionTest', coalesce(tp.plan_dilution_test, 0),
        'demos', coalesce(tp.plan_demos, 0),
        'fieldVisit', coalesce(tp.plan_field_visit, 0),
        'fieldDay', coalesce(tp.plan_field_day, 0),
        'dealerAppointment', coalesce(tp.plan_dealer_appointment, 0),
        'dealerAppointed', coalesce(tp.plan_dealer_appointed, 0)
      ),
      jsonb_build_object(
        'sales', coalesce(tp.sales, 0),
        'collection', coalesce(tp.collection, 0),
        'farmerContact', coalesce(tp.farmer_contact, 0),
        'gfm', coalesce(tp.gfm, 0),
        'ofm', coalesce(tp.ofm, 0),
        'nightHalt', coalesce(tp.night_halt, 0),
        'dilutionTest', coalesce(tp.dilution_test, 0),
        'demos', coalesce(tp.demos, 0),
        'fieldVisit', coalesce(tp.field_visit, 0),
        'fieldDay', coalesce(tp.field_day, 0),
        'dealerAppointment', coalesce(tp.dealer_appointment, 0),
        'dealerAppointed', coalesce(tp.dealer_appointed, 0)
      ),
      to_jsonb(tp),
      to_jsonb(tp),
      coalesce((
        select jsonb_agg((to_jsonb(de) - 'id') order by de.entry_date)
        from public.daily_entries de
        where de.person_id = tp.person_id
          and to_char(de.entry_date, 'YYYY-MM') = v_month_key
      ), '[]'::jsonb),
      now()
    from public.team_persons tp
    on conflict (month_key, person_id) do update set
      state_id = excluded.state_id,
      person_name = excluded.person_name,
      plan_data = excluded.plan_data,
      actual_data = excluded.actual_data,
      full_data = excluded.full_data,
      data = excluded.data,
      daily_records = excluded.daily_records,
      archived_at = excluded.archived_at;

    -- Start the new month at zero. Daily plan never carries into monthly plan.
    update public.team_persons set
      sales = 0, collection = 0,
      plan_sales = 0, plan_collection = 0,
      farmer_contact = 0, gfm = 0, ofm = 0, night_halt = 0,
      dilution_test = 0, demos = 0, field_visit = 0, field_day = 0,
      dealer_appointment = 0, dealer_appointed = 0,
      plan_farmer_contact = 0, plan_gfm = 0, plan_ofm = 0, plan_night_halt = 0,
      plan_dilution_test = 0, plan_demos = 0, plan_field_visit = 0, plan_field_day = 0,
      plan_dealer_appointment = 0, plan_dealer_appointed = 0,
      urea_qty = 0, urea_amt = 0, dap_qty = 0, dap_amt = 0,
      seeds_qty = 0, seeds_amt = 0, pesti_qty = 0, pesti_amt = 0,
      fert_qty = 0, fert_amt = 0;
  end if;

  -- Every date change clears both daily actual and daily plan fields.
  update public.team_persons set
    today_sales = 0, today_collection = 0,
    today_plan_sales = 0, today_plan_collection = 0,
    today_farmer_contact = 0, today_gfm = 0, today_ofm = 0,
    today_night_halt = 0, today_dilution_test = 0, today_demos = 0,
    today_field_visit = 0, today_field_day = 0,
    today_dealer_appointment = 0, today_dealer_appointed = 0,
    today_plan_farmer_contact = 0, today_plan_gfm = 0, today_plan_ofm = 0,
    today_plan_night_halt = 0, today_plan_dilution_test = 0, today_plan_demos = 0,
    today_plan_field_visit = 0, today_plan_field_day = 0,
    today_plan_dealer_appointment = 0, today_plan_dealer_appointed = 0,
    attendance = '',
    last_updated = (extract(epoch from clock_timestamp()) * 1000)::bigint;

  update public.app_settings
    set value = jsonb_build_object('business_date', p_today::text), updated_at = now()
  where key = 'business_calendar';

  return jsonb_build_object(
    'status', case when v_month_changed then 'month_archived' else 'day_rolled' end,
    'from_date', v_last_date,
    'business_date', p_today,
    'archived_month', case when v_month_changed then v_month_key else null end
  );
end;
$$;

grant execute on function public.hsr_rollover(date) to anon, authenticated;

notify pgrst, 'reload schema';
